### ISSUE TITLE
A possible addition to the gameplay mechanic to the toolbar

### ISSUE THREAD

**Issue by branman5949** [TCLProject/theoffhandmod#2]
Would it be possible if you could make this mod a little more like M&B Battlegear 2 by making it possible to swap to the regular original minecraft toolbar and then to the dual wielding toolbar like in M&B Battlegear 2?

**Comment by TCLProject** [comment]
No, unfortunately while that would be a good idea, that would be very difficult to make due to the way in which the mod works.
If you, or anyone, would like to implement it, I would welcome a PR though.
